# MySQL Connection
spring.datasource.url=jdbc:mysql://localhost:3306/sentinel_api?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

# MySQL Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate (JPA) Dialect for MySQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Auto DDL ? create / update schema
spring.jpa.hibernate.ddl-auto=update

# Show SQL in logs (optional)
spring.jpa.show-sql=true
